import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import HistoryCard from '../components/HistoryCard';
import { BackButton } from '../components/UI';

export default function HistoryPage({ history, onBack, onRepeat, onClear }) {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><BackButton onPress={onBack} /><View style={styles.heading}><Text style={styles.title}>Histórico de rotas</Text><Text style={styles.subtitle}>{history.length ? `${history.length} rota(s) concluída(s) neste aparelho` : 'Nenhuma rota concluída ainda'}</Text></View></View>{history.length ? <><Pressable onPress={onClear} style={styles.clear}><Text style={styles.clearText}>Limpar histórico</Text></Pressable>{history.map((route) => <HistoryCard key={route.id} route={route} onRepeat={onRepeat} />)}</> : <View style={styles.empty}><Text style={styles.emptyIcon}>◷</Text><Text style={styles.emptyTitle}>Seu histórico está vazio</Text><Text style={styles.emptyText}>As rotas aparecerão aqui somente depois que você calcular e concluir uma navegação.</Text></View>}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#111' }, content: { padding: 22, paddingBottom: 32 }, header: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 20 }, heading: { flex: 1 }, title: { color: '#f5f5f5', fontSize: 21, fontWeight: '900' }, subtitle: { color: '#0cc5d7', fontSize: 12, marginTop: 4 }, clear: { alignSelf: 'flex-end', padding: 8, marginBottom: 10 }, clearText: { color: '#ff9c9c', fontSize: 11, fontWeight: '800' }, empty: { backgroundColor: '#2a2a2a', borderRadius: 20, padding: 28, alignItems: 'center', marginTop: 40 }, emptyIcon: { color: '#0cc5d7', fontSize: 48 }, emptyTitle: { color: '#f5f5f5', fontSize: 18, fontWeight: '800', textAlign: 'center', marginTop: 10 }, emptyText: { color: '#999', textAlign: 'center', lineHeight: 18, fontSize: 12, marginTop: 8 }, });
