import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import MapSurface from '../components/MapSurface';
import { PrimaryButton, SearchBar } from '../components/UI';

export default function HomePage({ destinationText, setDestinationText, onSearch, onHistory, onGps, onSelectSuggestion, suggestions, searchingSuggestions, location, locationStatus, error, loading }) {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Text style={styles.wordmark}>Light Street</Text><Pressable onPress={onHistory} style={styles.headerLink}><Text style={styles.headerLinkText}>Histórico</Text></Pressable></View><SearchBar value={destinationText} onChangeText={setDestinationText} onSubmit={onSearch} suggestions={suggestions} onSelectSuggestion={onSelectSuggestion} searching={searchingSuggestions} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.mapWrap}><MapSurface location={location} /><View style={styles.mapOverlay}><Text style={styles.overlayTitle}>{location ? 'Sua localização' : 'Mapa mundial'}</Text><Text style={styles.overlayText}>{locationStatus}</Text></View></View><PrimaryButton onPress={onSearch} disabled={loading}>{loading ? 'Buscando destino...' : 'Encontrar rota'}</PrimaryButton><View style={styles.actions}><Pressable style={styles.action} onPress={onGps}><Text style={styles.icon}>◎</Text><View><Text style={styles.actionTitle}>Localização</Text><Text style={styles.actionText}>{location ? 'GPS conectado' : 'Ativar sensor GPS'}</Text></View></Pressable><Pressable style={styles.action} onPress={onHistory}><Text style={styles.icon}>◷</Text><View><Text style={styles.actionTitle}>Rotas concluídas</Text><Text style={styles.actionText}>Ver seu histórico real</Text></View></Pressable></View><Text style={styles.footer}>Digite um endereço e escolha uma sugestão para calcular a rota.</Text></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#111' }, content: { paddingHorizontal: 22, paddingTop: 16, paddingBottom: 32 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }, wordmark: { color: '#f5f5f5', fontSize: 28, fontWeight: '800', letterSpacing: -0.6 }, headerLink: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 15, backgroundColor: '#202020' }, headerLinkText: { color: '#0cc5d7', fontWeight: '700', fontSize: 12 }, mapWrap: { height: 360, borderRadius: 24, overflow: 'hidden', marginBottom: 16, backgroundColor: '#202020' }, mapOverlay: { position: 'absolute', top: 16, left: 16, backgroundColor: 'rgba(16,16,16,.78)', paddingVertical: 9, paddingHorizontal: 12, borderRadius: 12 }, overlayTitle: { color: '#f5f5f5', fontSize: 14, fontWeight: '800' }, overlayText: { color: '#b6c5c5', fontSize: 10, marginTop: 3 }, actions: { flexDirection: 'row', gap: 10 }, action: { flex: 1, minHeight: 78, borderRadius: 16, backgroundColor: '#202020', padding: 13, flexDirection: 'row', alignItems: 'center' }, icon: { fontSize: 23, color: '#0cc5d7', marginRight: 9 }, actionTitle: { color: '#f5f5f5', fontWeight: '800', fontSize: 12 }, actionText: { color: '#999', fontSize: 10, marginTop: 4 }, footer: { color: '#777', textAlign: 'center', fontSize: 11, marginTop: 26 }, error: { color: '#ff9c9c', textAlign: 'center', marginBottom: 12 }, });
