import { SafeAreaView, StyleSheet, Text, View } from 'react-native';
import MapSurface from '../components/MapSurface';
import { BackButton, PrimaryButton } from '../components/UI';
import { formatDistance, formatDuration } from '../services/routing';

export default function NavigationPage({ destination, location, route, trailCoordinates, isNavigating, startedAt, onBack, onStart, onFinish }) {
  const elapsedSeconds = isNavigating && startedAt ? Math.max(0, Math.round((Date.now() - startedAt) / 1000)) : route.durationSeconds;
  const actionLabel = isNavigating ? 'Finalizar rota' : 'Iniciar rota';

  return <SafeAreaView style={styles.safe}><View style={styles.screen}><View style={styles.mapArea}><MapSurface location={location} destination={destination} routeCoordinates={route.coordinates} trailCoordinates={trailCoordinates} followLocation={isNavigating} /><View style={styles.topBar}><BackButton onPress={onBack} /><View style={styles.destinationPill}><Text numberOfLines={2} style={styles.destination}>{destination.label}</Text></View></View></View><View style={styles.panel}><Text style={styles.kicker}>{isNavigating ? 'GPS ACOMPANHANDO · ' : 'PRONTO PARA INICIAR · '}{route.modeLabel.toUpperCase()}</Text><Text style={styles.title}>{isNavigating ? 'Tempo em movimento' : 'Tempo estimado'}</Text><Text style={styles.time}>{formatDuration(elapsedSeconds)}</Text><Text style={styles.meta}>{formatDistance(route.distanceMeters)} · {route.safetyLabel}</Text><PrimaryButton onPress={isNavigating ? onFinish : onStart}>{actionLabel}</PrimaryButton><Text style={styles.live}>{isNavigating ? 'O marcador acompanha sua localização e o caminho amarelo mostra o trajeto percorrido.' : 'Toque em “Iniciar rota” quando começar a andar. O GPS será acompanhado em tempo real.'}</Text><Text style={styles.note}>{isNavigating ? 'Finalize quando chegar ao destino. Só então o percurso será salvo no histórico.' : 'A rota planejada em azul aparece no mapa antes de você começar.'}</Text></View></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#111' }, screen: { flex: 1 }, mapArea: { height: '64%', position: 'relative' }, topBar: { position: 'absolute', top: 14, left: 18, right: 18, zIndex: 2, flexDirection: 'row', alignItems: 'center', gap: 12 }, destinationPill: { flex: 1, borderRadius: 25, paddingVertical: 11, paddingHorizontal: 18, backgroundColor: 'rgba(35,35,35,.95)' }, destination: { color: '#f5f5f5', fontWeight: '900', fontSize: 15 }, panel: { flex: 1, backgroundColor: '#111', marginTop: -18, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 26, paddingTop: 24, alignItems: 'center' }, kicker: { color: '#0cc5d7', fontWeight: '900', fontSize: 10, letterSpacing: 1.4, marginBottom: 14 }, title: { color: '#f5f5f5', fontWeight: '800', fontSize: 22, textAlign: 'center' }, time: { color: '#f5f5f5', fontSize: 44, fontWeight: '900', marginTop: 3 }, meta: { color: '#999', fontSize: 13, marginTop: 10, marginBottom: 24, textAlign: 'center' }, live: { color: '#0cc5d7', fontSize: 12, lineHeight: 17, textAlign: 'center', marginTop: 1 }, note: { color: '#777', fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 10 }, });
