import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import MapSurface from '../components/MapSurface';
import { BackButton, RouteCard } from '../components/UI';
import { formatDistance, formatDuration } from '../services/routing';

export default function RouteOptionsPage({ destination, location, routes, loading, error, onBack, onSelect }) {
  const safestScore = Math.max(...(routes || []).map((route) => route.lightingScore ?? -1));
  const previewRoute = routes?.[0];

  return <SafeAreaView style={styles.safe}><View style={styles.screen}><View style={styles.mapArea}><MapSurface location={location} destination={destination} routeCoordinates={previewRoute?.coordinates} /><View style={styles.topBar}><BackButton onPress={onBack} /><View style={styles.destinationPill}><Text numberOfLines={2} style={styles.destination}>{destination.label}</Text></View></View></View><ScrollView contentContainerStyle={styles.panel}><Text style={styles.kicker}>ROTAS CALCULADAS</Text><Text style={styles.heading}>{destination.label}</Text><Text style={styles.subheading}>A opção mais iluminada é destacada quando há dados de iluminação no OpenStreetMap.</Text>{loading ? <Text style={styles.info}>Calculando a pé, de bike e de carro...</Text> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{routes?.map((route) => <RouteCard key={route.modeId} title={route.modeLabel} icon={route.modeIcon} duration={formatDuration(route.durationSeconds)} distance={formatDistance(route.distanceMeters)} safetyLabel={route.safetyLabel} recommended={route.lightingScore !== null && route.lightingScore === safestScore} disabled={loading} onPress={() => onSelect(route)} />)}{!loading && !routes?.length ? <Text style={styles.error}>Não foi possível encontrar rotas para esse destino.</Text> : null}<Text style={styles.note}>A prioridade de iluminação usa vias com `lit=*` mapeadas no OpenStreetMap. Quando não há dados, o app informa em vez de inventar.</Text></ScrollView></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#111' }, screen: { flex: 1 }, mapArea: { height: '55%', minHeight: 330, position: 'relative' }, topBar: { position: 'absolute', top: 14, left: 18, right: 18, zIndex: 2, flexDirection: 'row', alignItems: 'center', gap: 12 }, destinationPill: { flex: 1, borderRadius: 25, paddingVertical: 11, paddingHorizontal: 18, backgroundColor: 'rgba(35,35,35,.95)' }, destination: { color: '#f5f5f5', fontWeight: '900', fontSize: 15 }, panel: { backgroundColor: '#111', padding: 22, borderTopLeftRadius: 28, borderTopRightRadius: 28, marginTop: -26, minHeight: 260 }, kicker: { color: '#0cc5d7', fontSize: 10, letterSpacing: 1.2, fontWeight: '800', textAlign: 'center' }, heading: { color: '#f5f5f5', fontSize: 18, fontWeight: '900', textAlign: 'center', marginTop: 7, marginBottom: 7 }, subheading: { color: '#999', fontSize: 11, lineHeight: 16, textAlign: 'center', marginBottom: 18 }, info: { color: '#999', textAlign: 'center', marginBottom: 12 }, error: { color: '#ff9c9c', textAlign: 'center', marginBottom: 12 }, note: { color: '#777', fontSize: 11, textAlign: 'center', lineHeight: 16, marginTop: 4 }, });
